### ISSUE TITLE
Find "Downfall" Attacks with Revizor?

### ISSUE THREAD

**Issue by 2steuer** [microsoft/sca-fuzzer#100]
Hi!
We're two cyber security students from Lübeck, Germany. We're currently working on a group project regarding Revizor and are seeking information from you, the experts :)
We've managed to reproduce your findings regarding Spectre, SCO and ZDI, which was already one of our project goals. We're now looking into the Downfall Attacks (https://downfall.page/media/downfall.pdf) and would like to see if we can maybe reproduce them using Revizor. As far as we understand, we would need to add support for the "gather" vector instruction to Revizor.
Now our humble questions before we start running:
Do you see any possibility to support fuzzing the given instruction(s) with Revizor? Could you give us a hint on how to add the instructions to the ISA information file, maybe adding a whole new contract for the vector instructions?

It would be very kind of you if you could give us pointers on where to start here.

Thank you!

Merlin + Lennart

**Comment by OleksiiOleksenko** [comment]
Hi,

In theory, it should be possible to detect the leak with the version of Revizor in `pre-release` branch. It already supports XMM registers, so you only need to add the corresponding instructions in the instruction set (add the necessary extension to the `download_spec ` command, and allow-list the instructions in the config file).

Mind, though, that this part of the instruction set have not been tested, so when you find a violation, be careful to minimize and root-cause it, because there are certain instructions that Unicorn emulates incorrectly, and it could cause a false positive.

Let us know about the results! I'm very curious :)

**Comment by 2steuer** [comment]
Hi!
Thanks a lot for your quick response, we'll look into that.
We only have around 2 weeks time for the project, so don't expect too much - but we will try our best.

I'll keep you posted.

Merlin

**Comment by 2steuer** [comment]
Okay, so we've come quite a little further today.
After some experimenting with adding the instructions to base.json ourselves (Kernel Panics are fun :-) ), we've decided there must be a way to tell revizor to do it.
So what we've done is:

- In get_spec.py: In parse_mem_operand, we've extended the check of VSIB == 0 to also allow XMM and YMM values. Until then, the memory operands were just not allowed and thus no gather instructions were added from the XML file.
- We've extended the x86_config.py default values to allow AVX2GATHER-AVX2GATHER and AVX512EVEX-GATHER categories.

Our config file we've tested with until now looks like follows:

```
# contract
contract_observation_clause: ct
contract_execution_clause:
  - seq

# tested instructions
instruction_categories:
  - BASE-BINARY
  - BASE-BITBYTE
  - AVX512EVEX-GATHER
  - AVX2GATHER-AVX2GATHER

# misc. fuzzing configuration
enable_speculation_filter: true
enable_observation_filter: true
enable_priming: false
input_gen_entropy_bits: 16
memory_access_zeroed_bits: 0
min_bb_per_function: 1
max_bb_per_function: 1
program_size: 16
avg_mem_accesses: 8
inputs_per_class: 2
executor_warmups: 2
x86_disable_div64: false
```

(based on the forshadow demo config file)

Et voilà, it at least starts! That already feels like a success for us. However, the code generation process seems to get operands for the gather instructions wrong in some cases. We've seen cases where revizor starts to fuzz, but then fails because the assembler code cannot be correctly compiled.

The output of `as` is the following:
```
bitschubser@nuc5:~/githome/preRelease/sca-fuzzer$ as generated.asm -o generated.o
generated.asm: Assembler messages:
generated.asm:38: Error: operand size mismatch for `vpgatherdd'
```


and I'll attach the generated.asm to this post.

Maybe if you'll find some time to have a look at this, we'd be very, very grateful for any help or advice given.

Thank you!

Merlin

Generated Assembler Code:
[generated.txt](https://github.com/user-attachments/files/15526081/generated.txt)

**Comment by OleksiiOleksenko** [comment]
Hi Merlin,

What you've done sounds reasonable. However, you're dealing with an instruction set not supported by Revizor, so be prepared to deal with bugs.

Keep in mind that Revizor doesn't support AVX, so any instructions using YMM registers won't work, and the same goes for mask registers `k*`. You'll have to find versions of the instruction that use only XMMs and GPRs, and you can tell the generator to use those instructions by using either `instruction_blocklist` or `instruction_allowlist` configuration options.

As for the `vpgatherdd` instruction, it looks like there is an issue with either the spec of the instruction, or with the way the generator interprets the spec, because the assembly you sent does not match this: https://www.felixcloutier.com/x86/vgatherqps:vgatherqpd

**Comment by 2steuer** [comment]
Hi Oleksii,
thanks for your input. We've handed in our project report with our findings.

Keep up the cool work!

Best Regards,
Merlin + Lennart
